#! /usr/bin/env ruby

require 'optparse'
# n - 数字表現
# s - 文字列表現(デフォルト)
# p - ()で囲う
params = ARGV.getopts('nsp')

from = ARGV[0]
to = ARGV[1]
if from =~ /^\d+$/ && params['n']
  from = from.to_i
  to = to.to_i
end

str = if params['p']
  if !params['n']
    joined = (from..to).to_a.map { |n| %Q!"#{n}"! }.join(', ')
    "(#{joined})"
  else
    joined = (from..to).to_a.join(', ')
    "(#{joined})"
  end
else
  (from..to).to_a
end

print str
